### ISSUE TITLE
Obstacles moving too quickly

### ISSUE THREAD

**Issue by TrueAegis** [Americollab/Evadgency#1]
In some cases the moving obstacles are moving proportionately too fast from one another.

- Not allowing for logical increase in difficulty by increasing speed with levels.

**Comment by TrueAegis** [comment]
You can probably resolve this and close it out James.

**Comment by TrueAegis** [comment]
Object movement speed is still too extreme in higher levels. Tested at level 30. Logic needs to be adjusted to allow for more reasonable increments of speed.

**Comment by jwrice1188** [comment]
Halved the increase in speed and adjusted math so speed would be between 1 and the incremented difficulty speed.
