### ISSUE TITLE
Game Information Running Off Screen

### ISSUE THREAD

**Issue by TrueAegis** [Americollab/Evadgency#8]
Game information at the bottom of the screen is running off the edges of the game window when it resizes for wide screens. 

- Does not seem to resize in relation to the window

![image](https://user-images.githubusercontent.com/27636112/75288179-68755700-57e1-11ea-94d0-760c716bd62a.png)

**Comment by jwrice1188** [comment]
What resolution was this instance?

**Comment by TrueAegis** [comment]
1920 x 1080. I suppose that would be helpful information.

**Comment by jwrice1188** [comment]
Removed font increase for larger screens
